### ISSUE TITLE
Detect unsupported features

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#109]
We need to disable some features for different document types (e.g.: Format DAX should not be available for VPAX files, Manage Dates for Datasets, etc...).

- [x] Add some attributes in the model returned by getModelFromXXX with the list of features and their availability (#121)
- [x] Add a specific screen in the UI when the feature is not available (done in #112)
- [x] Add UI support for the `AppFeature` enum (done in #137)
