### ISSUE TITLE
Format DAX improvements

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#116]
- [x] Allow resizing current/preview measure panes (done in #164)
- [x] Allow side over side comparison (done in #164)
- [x] Allow toggling word wrap (done in #164)
- [ ] Allow zooming the measures panes full screen
