### ISSUE TITLE
ManageDates configuration improvements

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#158]
- [x] host - add the `DateConfiguration.IsCurrent` property (details here #159)
- [x] host - set `DateConfiguration` defaults (`FirstMonthOfYear`, `FirstDayOfWeek`, `RegionalFormat`, `HolidaysCountry`) (details here #173)
- [x] host - support removing tables and measures by using `DateConfiguration` `IsEnabled` properties (details here #175)
- [x] UI - support changes and new properties (#178)
