### ISSUE TITLE
Special flag for columns created via Manage Dates

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#181]
Perhaps we need a special flag for tables if they have been previously created by Manage Dates so to avoid being selected for auto scan.

The table must be excluded if :
- `TabularTable.IsManageDates` = `true`
- `TabularTable.IsDateTable` = `true`
 
Task
- [x] host - add new `TabularTable.IsManageDates` property (#186) 
- [x] UI - add support for new property and exclusion logic (#187)
- [x] host - update Dax.Template package (#188)
