### ISSUE TITLE
Add "Download preview versions" option

### ISSUE THREAD

**Issue by danieleperilli** [sql-bi/Bravo#71]
Add an option in the About screen to allow users to be notified when a new preview version of Bravo is available.

- [x] Add new API option settings (completed with #82)
- [x] Add update settings in the About screen (done in #87)
- [x] #94
- [x] Check for updates on update channel change (done in #101)
