### ISSUE TITLE
Add support for application diagnostics

### ISSUE THREAD

**Issue by albertospelta** [sql-bi/Bravo#80]
- [x] Add diagnostics settings and API action (done/included in #81)
- [x] Add diagnostics console pane (done in #87)
- [x] Add Clear control (done in #107)
- [x] #100
- [x] Anonymize data if level is Basic (done in #107)
- [x] Log all calls  (auth, open, web messages, etc) (done in #107)
- [x] Avoid call api/GetDiagnostics while diagnostics is not enabled (done in #107)
