### ISSUE TITLE
Ignore minor differences in DAX Formatter

### ISSUE THREAD

**Issue by marcosqlbi** [sql-bi/Bravo#86]
We received this feedback: In my Contoso file from TDGTD I think, measures were already formatted, yet the tool says they can be formatted? Why? Even after I enabled automatic preview, it still shows the same number of measures that can be formatted. Or does it mean the measures aren’t read-only?

Probably most of the differences are caused by the initial CR/LF and following differences between CR/LF and CR or LF only that are not visible to the user.
We should verify whether this is the case and ignore these differences in the user notification (or add an option that controls whether the comparison should include CR/LF differences or not).

- [x] Normalize DAX spaces/CR/LF, add new format setting in Bravo (#118)
- [x] UI add the new `DaxLineBreakStyle` setting (#132)
- [x] Improve screen summary (#171)
- [x] further testing of the changes is required
